"""new field

Revision ID: 02794de263bd
Revises: 34abecc970a4
Create Date: 2023-05-22 01:26:09.068062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02794de263bd'
down_revision = '34abecc970a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('white_cards', sa.Column('is_selected', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('white_cards', 'is_selected')
    # ### end Alembic commands ###
