"""add field

Revision ID: 0306ee3f1a3c
Revises: 852cf9511c2b
Create Date: 2023-05-17 01:42:24.395637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0306ee3f1a3c'
down_revision = '852cf9511c2b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'is_admin')
    # ### end Alembic commands ###
