"""add new tables

Revision ID: 04d96cb0585f
Revises: 8f3e54a99a03
Create Date: 2023-05-15 23:44:22.953439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04d96cb0585f'
down_revision = '8f3e54a99a03'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scoreboard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('players', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['players'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_scores_m2m',
    sa.Column('scoreboard_id', sa.Integer(), nullable=True),
    sa.Column('player_scores_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_scores_id'], ['player_scores.id'], ),
    sa.ForeignKeyConstraint(['scoreboard_id'], ['scoreboard.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_scores_m2m')
    op.drop_table('rooms')
    op.drop_table('player_scores')
    op.drop_table('scoreboard')
    op.drop_table('players')
    # ### end Alembic commands ###
