"""add new field to player

Revision ID: 060dbddf327e
Revises: 0306ee3f1a3c
Create Date: 2023-05-19 00:52:41.440716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '060dbddf327e'
down_revision = '0306ee3f1a3c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_white_cards',
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['white_cards.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_white_cards')
    # ### end Alembic commands ###
