"""resolve issues

Revision ID: 110ee2eadef8
Revises: 04d96cb0585f
Create Date: 2023-05-15 23:58:32.555731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '110ee2eadef8'
down_revision = '04d96cb0585f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_scores')
    op.add_column('player_scores_m2m', sa.Column('player_id', sa.Integer(), nullable=True))
    op.drop_constraint('player_scores_m2m_player_scores_id_fkey', 'player_scores_m2m', type_='foreignkey')
    op.create_foreign_key(None, 'player_scores_m2m', 'players', ['player_id'], ['id'])
    op.drop_column('player_scores_m2m', 'player_scores_id')
    op.add_column('players', sa.Column('score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'score')
    op.add_column('player_scores_m2m', sa.Column('player_scores_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'player_scores_m2m', type_='foreignkey')
    op.create_foreign_key('player_scores_m2m_player_scores_id_fkey', 'player_scores_m2m', 'player_scores', ['player_scores_id'], ['id'])
    op.drop_column('player_scores_m2m', 'player_id')
    op.create_table('player_scores',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('player', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['player'], ['players.id'], name='player_scores_player_fkey'),
    sa.PrimaryKeyConstraint('id', name='player_scores_pkey')
    )
    # ### end Alembic commands ###
