"""add new col

Revision ID: 26d02305823c
Revises: c93b43983ad7
Create Date: 2023-05-16 00:21:52.876547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26d02305823c'
down_revision = 'c93b43983ad7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('scoreboard', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'rooms', 'scoreboard', ['scoreboard'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.drop_column('rooms', 'scoreboard')
    # ### end Alembic commands ###
