"""new field

Revision ID: 34abecc970a4
Revises: 060dbddf327e
Create Date: 2023-05-21 23:42:34.914023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34abecc970a4'
down_revision = '060dbddf327e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('game_is_started', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'game_is_started')
    # ### end Alembic commands ###
