"""add judge field

Revision ID: 6a81aeb347ca
Revises: 02794de263bd
Create Date: 2023-05-23 02:06:00.912730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a81aeb347ca'
down_revision = '02794de263bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('current_judge', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'rooms', 'players', ['current_judge'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.drop_column('rooms', 'current_judge')
    # ### end Alembic commands ###
