"""aa

Revision ID: 8460fd8bae19
Revises: 8c226ee85e5a
Create Date: 2023-05-23 23:31:25.104235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8460fd8bae19'
down_revision = '8c226ee85e5a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('player_scores_m2m_room_id_fkey', 'player_scores_m2m', type_='foreignkey')
    op.drop_constraint('player_scores_m2m_player_id_fkey', 'player_scores_m2m', type_='foreignkey')
    op.create_foreign_key(None, 'player_scores_m2m', 'players', ['player_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'player_scores_m2m', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'player_scores_m2m', type_='foreignkey')
    op.drop_constraint(None, 'player_scores_m2m', type_='foreignkey')
    op.create_foreign_key('player_scores_m2m_player_id_fkey', 'player_scores_m2m', 'players', ['player_id'], ['id'])
    op.create_foreign_key('player_scores_m2m_room_id_fkey', 'player_scores_m2m', 'rooms', ['room_id'], ['id'])
    # ### end Alembic commands ###
