"""add field

Revision ID: 852cf9511c2b
Revises: b67fd48cd0b4
Create Date: 2023-05-17 01:41:09.681090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '852cf9511c2b'
down_revision = 'b67fd48cd0b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
