"""aa

Revision ID: 8c226ee85e5a
Revises: 6a81aeb347ca
Create Date: 2023-05-23 23:20:15.735197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c226ee85e5a'
down_revision = '6a81aeb347ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
