"""add new tables

Revision ID: b67fd48cd0b4
Revises: 26d02305823c
Create Date: 2023-05-16 00:27:47.096304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b67fd48cd0b4'
down_revision = '26d02305823c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_scores_m2m',
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], )
    )
    op.drop_constraint('rooms_players_fkey', 'rooms', type_='foreignkey')
    op.drop_column('rooms', 'players')
    op.drop_column('rooms', 'scoreboard')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('scoreboard', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('rooms', sa.Column('players', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('rooms_players_fkey', 'rooms', 'players', ['players'], ['id'])
    op.drop_table('player_scores_m2m')
    # ### end Alembic commands ###
